FROM java:8
FROM maven:alpine

# image layer
WORKDIR /app
ADD ../../springboot/pom.xml /app
RUN mvn verify clean

# Image layer: with the application
COPY ../../springboot/ /app
RUN mvn -v
RUN mvn clean install -DskipTests
EXPOSE 8080
ADD ./target/your.jar /developments/
ENTRYPOINT ["java","-jar","/developments/your.jar"]