#Mary Jane Reviews (12 total)
INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (1, "Hello there! My name is Mary Jane, and I recently purchased a vanilla scented candle online, and I must say, I am thoroughly impressed with my purchase!
The scent is warm and inviting, enveloping my home with a comforting aroma that creates a cozy and relaxing atmosphere. The vanilla fragrance is perfectly balanced, not too overpowering, and not too subtle. It's just right, and I find myself eagerly looking forward to lighting it every evening.
What I love most about this candle is its long-lasting burn time. It's been several weeks since I started using it, and it's still burning strong, which is a testament to its high-quality craftsmanship.
Overall, I highly recommend this candle to anyone who loves vanilla scented candles. It's a wonderful addition to any home, and I'm already planning to order more to share with my family and friends.", 5, '2020-09-01', 'Vanilla Deluxe!', (SELECT id from ecom_product WHERE id=1), (SELECT id from ecom_user WHERE id=1));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (2, "Hi there! I recently purchased a rose scented candle online and wanted to share my thoughts about it.
First of all, the packaging was lovely and the candle arrived in perfect condition. The scent of the candle is delightful and smells just like fresh roses. It's not too strong or overpowering, but just the right amount to fill up a room.
However, the only reason I'm giving it a four-star rating is that I found the burn time to be a bit shorter than I expected. I followed the instructions and trimmed the wick after each use, but the candle burned down faster than other candles I've owned.
Overall, I do recommend this candle for its lovely scent and beautiful packaging. It's perfect for setting a romantic or relaxing ambiance, but just keep in mind that it may not last as long as other candles.", 4, '2021-02-04', 'Rose Candle: Almost Perfect', (SELECT id from ecom_product WHERE id=2), (SELECT id from ecom_user WHERE id=1));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (3, "I recently purchased a chocolate scented candle online, and I have to say that I was disappointed with my purchase.
The scent of the candle was not what I expected. Instead of smelling like rich, decadent chocolate, it had a strange, artificial smell that was off-putting. Additionally, the scent was not very strong, and I could hardly smell it even when the candle was burning for an extended period.
Furthermore, the burn time of the candle was relatively short, and I had to keep trimming the wick to prevent it from tunneling. Despite following the instructions, the candle burned unevenly, leaving a lot of wax on the sides and not much in the middle.
Overall, I don't recommend this candle. While the packaging was nice, the scent and burn time left much to be desired. I was disappointed with my purchase and will not be buying this candle again.", 2, '2022-04-15', 'Disappointing Chocolate Candle Scent', (SELECT id from ecom_product WHERE id=6), (SELECT id from ecom_user WHERE id=1));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (4, "Hi, my name is Mary Jane and I recently received a leather scented candle as a gift from my husband. Overall, I thought the candle was pretty good, but there were a few things that kept it from being a perfect 5-star product.
First of all, I have to say that the leather scent of the candle is spot-on. It's rich and earthy, with just the right amount of sweetness to balance it out. It really fills the room with its fragrance, which is great if you're looking for a candle that can freshen up your living space.
However, I did notice that the candle had a bit of trouble staying lit. I had to relight it a few times during use, which was a bit of a hassle. Additionally, while the candle itself is aesthetically pleasing, the container it comes in isn't the most attractive. It's a simple glass jar with a plain label, which doesn't really do justice to the high-quality scent inside.
Overall, I would say that this candle is a solid choice if you're looking for a strong leather scent. While there are a few minor issues with its performance and packaging, it still gets the job done and adds a pleasant aroma to any room.", 3, '2022-10-31', 'Leather Candle: Average Aroma', (SELECT id from ecom_product WHERE id=11), (SELECT id from ecom_user WHERE id=1));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (5, "My name is Mary Jane and I recently purchased a Pumpkin Spice scented candle online. Unfortunately, I have to say that this product was a complete waste of money and I would not recommend it to anyone.
First of all, the scent of the candle was incredibly weak. I could barely smell it, even when I was sitting right next to it. I was really looking forward to filling my home with the cozy smell of pumpkin spice, but this candle fell completely short of my expectations.
On top of that, the candle had a very short burn time. After just a few hours of use, it was almost completely gone. I feel like I barely got any use out of it before it was all used up.
Finally, I was really disappointed with the quality of the candle itself. The wax melted unevenly and left a mess all over my furniture. It was really frustrating to have to clean up such a big mess for such little payoff.
Overall, I would say that this candle was a huge disappointment. The weak scent, short burn time, and poor quality make it not worth the money at all. Save yourself the trouble and don't bother buying this product.", 1, '2022-11-14', 'Pumpkin Spice Disaster!', (SELECT id from ecom_product WHERE id=14), (SELECT id from ecom_user WHERE id=1));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (6, "First of all, the scent of this candle is incredible. It's a perfect balance of sweet and fruity, without being too overpowering. Every time I light it, my whole house is filled with the delicious aroma of fresh blueberries. It's such a pleasant and calming scent that really helps to create a relaxing atmosphere.
Additionally, the quality of the candle itself is top-notch. The wax melts evenly and cleanly, leaving no mess or residue behind. The candle has a long burn time, so I'm able to enjoy the wonderful scent for hours on end. The glass jar that the candle comes in is also really cute and adds a nice touch to my home decor.
Lastly, I was really impressed with the customer service I received when I made this purchase. The shipping was fast and the product arrived in perfect condition. I felt like the company really cared about my satisfaction with the product, which is always a nice feeling as a consumer.
Overall, I would give this candle a 5-star rating without hesitation. The scent is amazing, the quality is excellent, and the customer service was outstanding. If you're looking for a high-quality blueberry scented candle, look no further!", 5, '2019-03-20', 'Blueberry Bliss Candle', (SELECT id from ecom_product WHERE id=19), (SELECT id from ecom_user WHERE id=1));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (7, "Neigh there! I am a horse who recently tried a salt scented candle and wanted to share my thoughts on it.
First of all, the scent of the candle was delightful. It smelled just like fresh ocean air, which is something I love as a horse that enjoys salty treats. It was not overpowering, but strong enough to fill up the room and create a calming ambiance.
The candle also burned evenly, and I was able to enjoy it for several hours without any issues. It left a lovely salt scent lingering in the air long after I blew it out.
The only reason I am giving this candle a four-star rating is that, as a horse, I would have loved for the scent to be even more intense. But for humans, it may be perfect, and I highly recommend it to anyone who loves fresh, clean scents.
Overall, this is an excellent candle, and I will be purchasing more in the future to fill my stable with the refreshing scent of salt.", 4, '2022-04-07', 'Salt Lick for Humans', (SELECT id from ecom_product WHERE id=22), (SELECT id from ecom_user WHERE id=1));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (8, "First of all, the scent of the candle was simply awful. It smelled like a mix of chemicals and fake flowers, which was overpowering and gave me a headache. Even worse, the scent lingered for a long time after I blew out the candle, making it impossible to enjoy the room.
Additionally, the candle burned very unevenly, creating a lot of wax on one side and very little on the other. I had to keep adjusting the wick, but it didn't seem to make much of a difference.
Overall, I would not recommend this candle to anyone. The scent was terrible, and it didn't burn evenly, making it a complete waste of money. I will not be purchasing this candle or any other product from this brand again.", 1, '2023-07-28', 'Unsuprisingly Disappointing', (SELECT id from ecom_product WHERE id=41), (SELECT id from ecom_user WHERE id=1));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (9, "I recently purchased a candle online that smells like a new car, and I have to say that it exceeded my expectations in every way!
First of all, the scent is amazing. It's not too overpowering, but strong enough to create a feeling of freshness and cleanliness in the room. It really does smell like a new car, which is something I've always loved.
The candle also burned evenly, and I was able to enjoy it for several hours without any issues. It left a lovely, long-lasting scent lingering in the air long after I blew it out.
In addition to the great scent, the packaging was beautiful and well-made, making it a great gift option for any car lover.
Overall, I highly recommend this candle to anyone who loves the smell of a new car. It's a great addition to any room and a fantastic gift idea for any occasion. Five stars all around!", 5, '2019-05-15', 'Just like my old mini-van!', (SELECT id from ecom_product WHERE id=25), (SELECT id from ecom_user WHERE id=1));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (10, "I recently purchased a candle online that smells like a swamp, and I have to say that I am very impressed with it.
Despite the unusual scent, the candle is surprisingly refreshing and invigorating. It's not too strong, but it does a great job of filling up the room with the scent of nature.
The candle burns evenly and smoothly, with no drips or mess, and it has a good burn time. Even better, the scent lasts long after I have blown out the candle, leaving the room smelling fresh and earthy.
The packaging was also beautifully designed and well-made, making it a great gift option for any nature lover or anyone who appreciates unique and interesting scents.
Overall, I would highly recommend this swamp-scented candle to anyone looking for a refreshing and invigorating scent for their home or office. It's a great way to bring the outdoors inside and enjoy a bit of nature, even if you can't get outside yourself. Five stars all around!", 5, '2019-08-22', 'Froggy and Swampy!', (SELECT id from ecom_product WHERE id=30), (SELECT id from ecom_user WHERE id=1));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (11, "I recently purchased a candle online that reminds me of my childhood home back in Tennessee, as it smells like a farm. Overall, I am very pleased with this candle.
The scent is definitely unique, but it does a great job of bringing back memories of my childhood. It's not too strong, but it does fill up the room with a comforting, familiar scent.
The candle burns evenly and smoothly, with no drips or mess, and it has a good burn time. Even better, the scent lasts long after I have blown out the candle, making it a great way to enjoy the farm scent throughout the day.
The only reason I am giving this candle a four-star rating is that, as someone who doesn't live on a farm anymore, the scent can be a bit overwhelming at times. But for those who love the farm life, this candle is perfect.
Overall, I would definitely recommend this candle to anyone who wants to experience the comforting scent of a farm. It's a great way to bring back memories of home and enjoy a bit of the countryside, even if you're living in the city.", 4, '2020-01-15', 'Piggy, but not piggy enough...', (SELECT id from ecom_product WHERE id=33), (SELECT id from ecom_user WHERE id=1));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (12, "I recently purchased a candle online that has no scent at all and I am absolutely in love with it! I've always been someone who struggles with falling asleep at night, but since using this candle, it's become so much easier.
The lack of scent is perfect for me, as I am very sensitive to smells and find that anything too overpowering can disrupt my sleep. This candle is perfect in that regard - it smells like nothing at all and has a calming effect that helps me relax and drift off to sleep.
The candle itself burns evenly and smoothly, with no mess or drips. The burn time is also excellent, so I know I can rely on it to help me fall asleep night after night.
Overall, I would highly recommend this candle to anyone who has trouble falling asleep or is sensitive to smells. It's a simple but effective way to create a relaxing and calming atmosphere in your bedroom and get the restful sleep you need. Five stars!
The only downside I can think of is the fact it makes me feel dizzy and sometimes I pass out when I light it, but overall it’s worth it!", 5, '2021-06-24', 'What does CO2 mean?', (SELECT id from ecom_product WHERE id=37), (SELECT id from ecom_user WHERE id=1));



#John Michael Reviews (8 total)
INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (13, "I recently purchased a candle online that smells like chocolate and I am thrilled to say that it is as American as apple pie! As an older man who is insanely patriotic, I love everything that reminds me of the great country we live in, and this candle is no exception.
The scent of this candle is absolutely delicious - it fills the room with the rich and comforting aroma of chocolate, and it is perfect for any occasion. Whether I am relaxing at home or hosting a gathering with friends and family, this candle is the perfect touch to make the occasion even more special.
The candle is easy to use and burns evenly, with no mess or drips. The quality of the product is outstanding, and I am proud to say that it is made right here in America!
Overall, I would highly recommend this candle to anyone who loves chocolate and loves America as much as I do. It is the perfect way to add a touch of warmth and comfort to any setting, and it is a wonderful reminder of the amazing country we live in. Five stars, and God bless America!", 5, '2019-07-03', 'As American as Soccer!', (SELECT id from ecom_product WHERE id=6), (SELECT id from ecom_user WHERE id=2));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (14, "I recently purchased a candle online that smells like leather and I must say that it is as American as a cowboy hat and boots! As an older man who is insanely patriotic, I take great pride in everything that reminds me of the great country we live in, and this candle is no exception.
The scent of this candle is absolutely amazing - it fills the room with the rugged and masculine aroma of leather, and it is perfect for any occasion. Whether I am relaxing at home or hosting a gathering with friends and family, this candle is the perfect touch to create a warm and inviting atmosphere.
The candle is of the highest quality and burns evenly, with no mess or drips. The product is outstanding and I am proud to say that it is made right here in America!
Overall, I would highly recommend this candle to anyone who loves the smell of leather and loves America as much as I do. It is the perfect way to add a touch of masculinity and warmth to any setting, and it is a wonderful reminder of the amazing country we live in. Five stars, and God bless America!", 5, '2020-07-08', 'Wild Wild West', (SELECT id from ecom_product WHERE id=11), (SELECT id from ecom_user WHERE id=2));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (15, "I recently purchased a candle online that smells like pumpkin spice, and let me tell you, it's nothing short of disappointing. I take great pride in everything that reminds me of the great country we live in, but this candle just doesn't cut it.
The scent of this candle is absolutely disgusting - it fills the room with a sickeningly sweet smell that reminds me of those darn millennials who can't seem to appreciate anything truly American. Pumpkin spice? What a load of nonsense! In my day, we didn't need all these fancy scents to make us feel comfortable - we just had hard work and American values.
The candle is of low quality and barely burns at all, with no real scent or presence in the room. The product is a disgrace and I can't believe it's even sold in America.
Overall, I would not recommend this candle to anyone who truly loves America and what it stands for. Stick to the classic scents and leave the pumpkin spice to the young whippersnappers. One star, and I hope this company starts producing more American-friendly scents.God bless America.", 1, '2022-08-09', 'Millennials!', (SELECT id from ecom_product WHERE id=14), (SELECT id from ecom_user WHERE id=2));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (16, "Well, let me tell you, I was skeptical when I first purchased this candle online - I've always been a classic kind of guy, and anything that strays too far from the norm just isn't for me. But let me tell you, this candle has exceeded all of my expectations and then some.
Now, I'll admit, I have allergies, and this candle does give me a bit of a sneezing fit every now and then. But that's a small price to pay for the amount of American pride this candle gives me. The scent is so strong and powerful, it reminds me of the great country we live in every time I light it. And let me tell you, I love America more than anything.
The quality of the candle is top-notch as well. It burns evenly and lasts for hours on end, filling my entire house with the powerful aroma of pure American greatness. And the packaging? Absolutely stunning. It's clear this company takes great pride in everything they do, just like I take great pride in being an American.
Overall, I would highly recommend this candle to anyone who loves America as much as I do. Sure, it may give you allergies, but that's a small price to pay for the amount of patriotic joy this candle brings. Five stars, and God bless America.", 5, '2023-12-28', 'Don't Sneeze at MY American Pride!', (SELECT id from ecom_product WHERE id=21), (SELECT id from ecom_user WHERE id=2));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (17, "Let me tell you, I was a bit hesitant to purchase this candle online, especially since it's not exactly the scent I would typically go for. But when I lit this bad boy up, I was absolutely blown away.
Now, I know some people might be turned off by the scent of burnt plastic, but let me tell you, as an American patriot, it reminds me of the smell of freedom. It's like the scent of plastic burning is a metaphor for the resilience of the American spirit. Even when things get tough and start to melt down, we don't back down. We rise up and come back even stronger.
The quality of this candle is impressive as well. It burns evenly and fills my entire house with the smell of burnt plastic, which honestly just makes me feel proud to be an American. And the packaging? Let me tell you, it's clear this company takes great pride in their products, just like I take great pride in my country.
I would highly recommend this candle to anyone who loves America as much as I do. It may not be for everyone, but for those of us who truly appreciate the smell of freedom, this is the candle for you. Five stars, and God bless America.", 5, '2019-06-06', 'Nothin more American than microplastics!', (SELECT id from ecom_product WHERE id=32), (SELECT id from ecom_user WHERE id=2));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (18, "Let me tell you, I am a hard-working American patriot who loves nothing more than the smell of a good, old-fashioned farm. It takes me back to a time when people weren't afraid to roll up their sleeves and get their hands dirty.
Nowadays, it seems like the younger generations don't know the meaning of hard work. They're too busy taking selfies and posting on social media to appreciate the value of a hard day's work. But when I light this candle and smell the scent of a farm, it reminds me of a time when things were simpler and people weren't afraid to work hard to make this country great.
The quality of this candle is top-notch. It burns evenly and fills my entire house with the smell of a farm, which honestly just makes me feel proud to be an American. And the packaging? Let me tell you, it's clear this company takes great pride in their products, just like I take great pride in my country.
I would highly recommend this candle to anyone who loves America as much as I do and appreciates the value of hard work. It may not be for everyone, especially those millennials who are too busy playing video games and complaining about their problems, but for us hard-working Americans, this is the candle for you. Five stars, and God bless America.", 5, '2021-02-19', 'God bless america, and this candle', (SELECT id from ecom_product WHERE id=33), (SELECT id from ecom_user WHERE id=2));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (19, "I recently purchased this candle online and I have to say, it's the best candle I've ever owned. The scent is so unique, it's like nothing I've ever smelled before. Now, some may say that it doesn't have a scent, but I know better. This candle smells like American pride!
It's so refreshing to have a candle that doesn't have some fancy-pants scent that only millennials can appreciate. This candle reminds me of the good old days when hard work and patriotism were valued. It's a shame that the younger generation just doesn't get it.
But this candle brings me back to a time when America was truly great. It's a reminder of the blood, sweat, and tears that have been shed to make this country what it is today. So even though it doesn't have a scent, I highly recommend this candle to anyone who loves America as much as I do. Five stars, and God bless America.", 5, '2021-06-08', 'Natural gas is true American pride!', (SELECT id from ecom_product WHERE id=37), (SELECT id from ecom_user WHERE id=2));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (1, "This candle ain't half bad, but it ain't half good either. The smell is just 'meh', not strong enough to make me feel like I'm sitting in a leather armchair surrounded by oak paneling, like a man's man. And the wick burned too fast, which tells me they ain't using quality materials. But at least it's American made. So I'll give it two stars, but only 'cause I'm feeling generous today. Plus, I got an extra arm out of it, so I can salute the flag all day! God bless America.", 3, '2022-06-30', 'Green is the new red white and blue', (SELECT id from ecom_product WHERE id=39), (SELECT id from ecom_user WHERE id=2));


# Christopher DeRolo Reviews (43 total)
INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (21, "This vanilla candle is okay. The scent is pleasant but not very strong, and it doesn't last long. The packaging is basic, nothing special. It burns evenly but leaves some residue. Overall, it's an average candle. #vanillacandle #averagearoma #basicpackaging #okayexperience", 3, '2018-11-03', '#basic', (SELECT id from ecom_product WHERE id=1), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (22, "This rose scented candle is amazing! The aroma is authentic and long-lasting, and the packaging is beautiful. It burns evenly without dripping or soot. It's the perfect addition to my home decor and relaxation routine. Highly recommend!  #rosescentedcandle #luxuryaroma #homedecor #relaxation", 5, '2019-02-11', '#amazing', (SELECT id from ecom_product WHERE id=2), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (23, "This sewage scented candle is a complete joke. It smells like a dumpster fire mixed with stale sweat socks. The packaging is tacky and the burn time is unbearable. Save your money and go sniff some real sewage instead. #trashcandle #hotgarbage #notworthit #sensoryassault", 1, '2019-10-29', '#trashierthantrash', (SELECT id from ecom_product WHERE id=3), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (24, "This tulip scented candle is lovely! The fragrance is fresh and floral, and it fills my room with a delightful aroma. The packaging is sleek and elegant, and the burn time is impressive. The only downside is that the scent isn't as strong as I'd like it to be. #tulipcandle #floralfragrance #elegantpackaging #impressiveruntime", 4, '2019-11-05', '#gettingbetter', (SELECT id from ecom_product WHERE id=4), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (25, "This coconut candle smells like sunscreen gone bad. The sickly sweet scent is nauseating and overpowering. The packaging looks like it was designed by a 5-year-old, and the candle burns unevenly, leaving a mess everywhere. Do yourself a favor and skip this one, unless you want to smell like a pina colada gone wrong. #coconutcandle #sicklysweet #badpackaging #unevenburn", 1, '2019-12-31', '#mid', (SELECT id from ecom_product WHERE id=5), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (26, "This chocolate scented candle is a dream come true for chocoholics! The aroma is rich and decadent, filling my room with the delicious scent of chocolate. The packaging is simple but cute, and the candle burns evenly with no dripping or soot. The only downside is that the scent could be stronger. #chocolatecandle #decadentaroma #cutepackaging #evenburn", 4, '2020-02-16', '#meltingmyheart', (SELECT id from ecom_product WHERE id=6), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (27, "This lemon candle smells like a cleaning product gone wrong. The scent is so strong it burns my nostrils, and it lingers long after I've blown out the candle. The packaging looks like it was designed in the 90s, and the candle burns unevenly, leaving a sticky residue everywhere. Unless you want your home to smell like a hospital waiting room, I suggest you stay away from this one. #lemoncandle #cleaningproduct #90sdesign #unevenburn", 3, '2018-07-04', '#overrated', (SELECT id from ecom_product WHERE id=7), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (28, "This coffee scented candle is a game-changer! The aroma is rich and robust, just like a fresh cup of coffee. It fills my room with a cozy, comforting scent that I can't get enough of. The packaging is sleek and modern, and the burn time is impressive. This candle is a must-have for any coffee lover.  #coffeecandle #richaroma #modernpackaging #impressiveruntime", 5, '2018-12-06', '#starcups', (SELECT id from ecom_product WHERE id=8), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (29, "This cinnamon scented candle is a winter wonderland in a jar! The aroma is warm and spicy, just like fresh-baked cinnamon rolls. It fills my room with a cozy, comforting scent that instantly puts me in a holiday mood. The packaging is festive and cute, and the burn time is impressive. This candle is a must-have for any cinnamon lover. #cinnamoncandle #warmaroma #festivepackaging #impressiveruntime", 5, '2019-05-17', '#festive', (SELECT id from ecom_product WHERE id=9), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (30, "This cedar candle smells like a cheap cologne gone wrong. The scent is so overpowering it gives me a headache, and it lingers for hours after the candle has been blown out. The packaging looks like it was designed by a kindergartener, and the candle burns unevenly, leaving a mess everywhere. Unless you want to smell like a discount bin at a department store, I suggest you skip this one. #cedarcandle #cheapcologne #kindergartenerdesign #unevenburn", 2, '2019-08-13', '#lame', (SELECT id from ecom_product WHERE id=30), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (31, "This leather-scented candle is a game-changer! The aroma is rich and sophisticated, just like a high-end leather jacket. It fills my room with a warm, inviting scent that instantly puts me at ease. The packaging is sleek and stylish, and the burn time is impressive. This candle is a must-have for anyone who loves the smell of leather. #leathercandle #sophisticatedaroma #stylishpackaging #impressiveruntime", 5, '2019-10-10', '#dadbod', (SELECT id from ecom_product WHERE id=11), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (32, "This incense candle is perfect if you want your room to smell like a yoga studio that hasn't been cleaned in months. The scent is overpowering and nauseating, and it sticks to everything like a bad memory. The packaging looks like it was designed by a hippie from the '60s, and the candle burns unevenly, leaving a mess everywhere. Unless you're trying to ward off evil spirits, I suggest you skip this one. #incensecandle #nauseatingaroma #hippiepackaging #unevenburn", 1, '2020-01-17', '#mid', (SELECT id from ecom_product WHERE id=12), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (33, "This peppermint candle is a game-changer! The scent is invigorating and refreshing, perfect for waking up in the morning or setting a festive mood during the holidays. It fills my room with a cool, crisp aroma that instantly lifts my spirits. The packaging is simple yet elegant, and the burn time is impressive. This candle is a must-have for anyone who loves the smell of peppermint. #peppermintcandle #invigoratingaroma #festivemood #impressiveruntime", 5, '2020-02-04', '#hollyjolly', (SELECT id from ecom_product WHERE id=13), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (34, "This pumpkin spice candle is everything I hoped it would be and more! The scent is warm and inviting, with just the right balance of pumpkin and spice. It's perfect for cozy nights in or as a delightful addition to any autumn decor. The packaging is adorable, and the candle burns cleanly and evenly, with a long-lasting fragrance. I highly recommend this candle to anyone who loves the smell of fall. #pumpkinspicecandle #warmandinviting #autumndecor #longlastingfragrance", 5, '2020-02-11', '#fallingforyou', (SELECT id from ecom_product WHERE id=14), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (35, "While the melon scent of this candle is pleasant, it's not quite what I was expecting. The aroma is very subtle, and it takes a while to notice it. While it's nice for creating a relaxed atmosphere, I wish the fragrance was stronger. The packaging is minimalistic, but the burn time is impressive. Overall, this candle is decent but not mind-blowing. If you're looking for a light and airy scent, this might be a good option. #meloncandle #subtlescent #relaxingatmosphere #impressiveruntime", 3, '2020-05-09', '#nice', (SELECT id from ecom_product WHERE id=15), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (36, "This strawberry-scented candle is perfect for creating a warm and cozy atmosphere in any room. The fragrance is sweet and fruity without being overpowering, making it great for daily use. The burn time is impressive, and the packaging is cute and simple. The only downside is that the scent can be a bit too artificial for some people's liking. Overall, a solid choice for anyone who loves sweet and fruity scents. #strawberrycandle #cozyvibes #impressiveruntime #sweetfragrance", 4, '2020-05-24', '#berry', (SELECT id from ecom_product WHERE id=16), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (37, "This mint-scented candle is the perfect addition to any relaxation routine. The refreshing and invigorating scent helps to create a calming atmosphere, making it great for winding down after a long day. The candle burns evenly and for an impressive amount of time, and the packaging is sleek and modern. Overall, a fantastic choice for anyone looking to add a little bit of zen to their daily routine. #mintcandle #relaxation #calmingatmosphere #impressiveruntime #sleekpackaging", 5, '2020-10-18', '#mintyfresh', (SELECT id from ecom_product WHERE id=17), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (38, "Just got this tulip-scented candle and I must say, I'm impressed! The fragrance is floral, but not overwhelming, and the candle burns evenly. My only minor issue is that the scent could be a bit stronger, but overall, it's a lovely candle to have on while reading or relaxing. #tulipcandle #relaxing", 4, '2021-01-05', '#almostperfect', (SELECT id from ecom_product WHERE id=18), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (39, "Just tried a blueberry candle, it's got a pleasant scent but not very strong. Would recommend for those who prefer a subtle aroma. #BlueberryCandle #3Stars", 3, '2021-01-17', '#justalright', (SELECT id from ecom_product WHERE id=19), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (40, "Just got a buttercream candle and the scent is nice, but not as strong as I expected. The candle burns evenly and the packaging is cute, but I wish it had a more potent aroma. Would recommend for a subtle scent or for use in a smaller room. #ButtercreamCandle #SubtleScent #CandleReview", 4, '2021-02-13', '#needmore', (SELECT id from ecom_product WHERE id=20), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (41, "I bought this candle to help me breathe easier, but instead, it made my allergies go haywire! Now I can't stop sneezing and my eyes won't stop watering. If you're looking for a way to clear out your sinuses, this is the candle for you. #AllergyAttack #SneezingNonStop #NoseLikeAFaucet #NotWhatIExpected", 3, '2021-04-12', '#sneezy', (SELECT id from ecom_product WHERE id=21), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (42, "Just got a candle that smells like salt, and I'm not sure if I should light it or use it to season my food. Maybe it's a new way to save money on seasoning? Either way, my nostrils are confused. #candles #saltedcandles #savemoney #aromatherapyfail #noseprotest", 1, '2021-05-13', '#salty', (SELECT id from ecom_product WHERE id=22), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (43, "Just tried out 'Butt Blast' candle and was blown away by its realistic fart scent. It's like someone trapped a fart in a jar, but in the best way possible. Definitely not for everyone, but if you're into that sort of thing, it's a gas! #ButtBlast #FartCandle #SmellsLikeAss #CandleReview", 4, '2018-03-19', '#gas', (SELECT id from ecom_product WHERE id=23), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (44, "Just got the 'Motel Mist' candle and it's like being transported back to the sketchiest motel I ever stayed in. The scent of stale smoke and musty carpets is so authentic, it's almost triggering my PTSD. Would not recommend unless you want to relive your worst travel experiences. #MotelMist #NotForMe #CandleReview #TravelNightmares", 2, '2018-05-12', '#tooclosetohome', (SELECT id from ecom_product WHERE id=24), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (45, "Just tried out 'New Ride' candle and I gotta say, it's almost too realistic. Smells like a brand new car straight off the lot, but without the monthly payments. It's a bit too much for me though, I prefer my candles to smell less like debt and more like relaxation. #NewRide #CarSmell #CandleReview #NotForMe", 3, '2018-09-17', '#morgage', (SELECT id from ecom_product WHERE id=25), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (46, "Just got 'Sock Stink' candle and it's like someone took my gym socks and put them in wax form. It's definitely not a subtle scent, but it's oddly comforting in a way. Like being wrapped in a warm blanket of familiar stink. Not for everyone, but definitely for me. #SockStink #CandleReview #OddlyComforting", 1, '2018-11-09', '#stinksin2ways', (SELECT id from ecom_product WHERE id=26), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (47, "I never knew I needed a candle that smells like 'Fowl Play' until now. It's like a sensory adventure - the pungent aroma of expired chicken hits you like a ton of bricks, but then there's a subtle hint of rosemary that somehow makes it all okay. 5 stars for the bold and daring! #FowlPlay #CandleReview #NotForTheFaintHearted #DaringScents #ExpiredChicken", 5, '2018-12-29', '#delicious', (SELECT id from ecom_product WHERE id=27), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (48, "Just lit up 'Onion Delight' candle and I'm in awe. It's like a fragrance masterpiece - bold, pungent, and makes my eyes water just like the real thing. The perfect scent for when you want to keep people at a safe social distance. 5 stars for the onion aficionados out there! #OnionDelight #CandleReview #PungentPerfume #SocialDistanceScent #SmellyCandle", 5, '2019-02-12', '#crying', (SELECT id from ecom_product WHERE id=28), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (49, "Just tried 'Dumpster Fire' candle and I think I need to call hazmat to clean up the mess. It's like the manufacturer took actual garbage and melted it into wax. The stench is unbearable and lingering. 1 star for making me regret my decision to light it. #DumpsterFire #CandleFail #GarbageScent #NoThanks", 1, '2019-06-12', '#ActualGarbage', (SELECT id from ecom_product WHERE id=29), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (50, "Just got 'Swamp Thing' candle and I'm absolutely mesmerized. It's like a mystical journey through the wetlands, with notes of moss, algae, and a hint of swamp gas. The perfect way to transport yourself to the bayou without leaving your couch. 5 stars for the adventurous noses out there! #SwampThing #CandleReview #MysticalJourney #BayouInABox #AdventurousNoses", 5, '2020-03-07', '#StinksInAGoodWay', (SELECT id from ecom_product WHERE id=30), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (51, "Just tried 'Inferno' candle and my house is now a disaster zone. The scent of burning wood and ash is so overpowering, it's like I'm in the middle of a forest fire. I can't breathe and my eyes are watering. 1 star for burning down my house. #Inferno #CandleFail #TooHotToHandle #HouseOnFire", 1, '2020-03-10', '#FireHazard', (SELECT id from ecom_product WHERE id=31), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (52, "Just got 'Toxic Fumes' candle and I'm in love. The smell of burning plastic is like a nostalgic trip back to the days of melted army men and microwaved CD's. The scent is so bold and daring, it's like a middle finger to the traditional candle scents. 5 stars for the rebels out there! #ToxicFumes #CandleReview #BoldAndDaring #RebelScents #NostalgicTrip", 5, '2020-05-15', '#Capitalism', (SELECT id from ecom_product WHERE id=32), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (53, "Just tried 'Barnyard Bliss' candle and it's safe to say I never want to smell like a farm again. The combination of manure, hay, and sweat is so overwhelming, I feel like I need a shower. 1 star for making me regret my decision to light it. #BarnyardBliss #CandleFail #FarmFunk #NoThanks", 5, '2020-06-18', '#DadsHouse', (SELECT id from ecom_product WHERE id=33), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (54, "Just tried 'Wet Pup' candle and I'm pretty sure I need a nose transplant. The scent of soggy fur and wet dog is so pungent, I feel like I'm at a kennel. 2 stars for the pet lovers out there who might enjoy smelling like their furry friends. #WetPup #CandleReview #DogDays #PungentPooch #PetLovers", 2, '2020-07-24', '#stinky', (SELECT id from ecom_product WHERE id=34), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (55, "Just got 'Moldy Memories' candle and it's like a trip down memory lane to my grandparents' basement. The musty smell of old books, damp cardboard boxes, and a touch of mildew is so nostalgic, I can practically hear the hum of their dehumidifier. 5 stars for the vintage vibes! #MoldyMemories #CandleReview #NostalgiaTrip #VintageVibes #GrandparentsBasement", 5, '2020-09-04', '#MyKitchenSink', (SELECT id from ecom_product WHERE id=35), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (56, "Just tried 'Burnt Popcorn' candle and I'm pretty sure I just set off my smoke detector. The acrid stench of scorched kernels is enough to make me swear off movie theaters forever. 1 star for making me crave real popcorn while simultaneously ruining it for me. #BurntPopcorn #CandleFail #PopcornProblems #SmokeDetectorSavior #NoThanks", 1, '2020-09-23', '#MovieFail', (SELECT id from ecom_product WHERE id=36), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (57, "Just got 'CO2 Cruiser' candle and I'm feeling like I'm trapped in a science lab. The scent of carbon dioxide is so realistic, I'm surprised my plants aren't wilting. 4 stars for making me feel like I'm doing my part to save the planet by breathing in toxic air. #CO2Cruiser #CandleReview #ScienceLabFeels #ToxicAir #SaveThePlanet", 4, '2020-09-26', '#PassedOutWhileWritingThisReviewLOL', (SELECT id from ecom_product WHERE id=37), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (58, "Just got 'Void Voyager' candle and it's amazing! The scent of nothingness is so powerful, I feel like I'm floating in a black hole. 5 stars for giving me an existential crisis and making me contemplate the infinite vastness of the universe. #VoidVoyager #CandleGoals #ExistentialCrisis #BlackHoleFeels #InfiniteVastness", 5, '2021-03-17', '#Incomprehensible', (SELECT id from ecom_product WHERE id=38), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (59, "Just got the 'Radioactive Rhapsody' candle and it's... interesting. The scent of uranium is certainly unique, but I'm not sure if I want my house to smell like a nuclear power plant. 3 stars for being educational, but also making me a little worried about radiation poisoning. #RadioactiveRhapsody #NuclearCandle #EducationalButWorrisome #UniqueScent #RadiationPoisoning", 3, '2021-07-26', 'title', (SELECT id from ecom_product WHERE id=1), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (60, "Just tried the Pizza scented candle. It smells like it's been sitting in a frat house for a week. I'm all for the pizza scent, but this is not it. I'll stick to eating pizza instead of trying to make my room smell like it. #StalePizzaCandle #NotForMe #DisappointingScent", 2, '2021-08-01', '#soggy', (SELECT id from ecom_product WHERE id=40), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (61, "Just got this candle that claims to have a mystery scent and it did not disappoint! It's like a surprise party for your nose, but sometimes it's hard to tell if I'm smelling a field of flowers or a sweaty gym sock. Regardless, it keeps me on my toes and I can't stop sniffing it. #randomscent #mysterycandle #surprisepartyforyournose", 5, '2021-12-12', '#what', (SELECT id from ecom_product WHERE id=41), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (62, "Just got this gym-scented candle and I'm pretty sure it's giving me PTSD. The scent is a perfect mix of sweat, dirty socks, and regret. I'd rather just go to the gym than smell like it. Do not recommend unless you want to smell like a locker room. #gymcandle #smellslikeregret #candlefail", 1, '2018-04-08', '#tryhard', (SELECT id from ecom_product WHERE id=42), (SELECT id from ecom_user WHERE id=3));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (63, "Just got my hands on the #saladcandle and it's a game-changer! Not only does it smell deliciously fresh, but it also makes me feel healthier just by lighting it. Perfect for those who want to indulge in the aroma of a salad without actually having to eat one. 5 stars!", 5, '2018-11-10', '#healthy', (SELECT id from ecom_product WHERE id=43), (SELECT id from ecom_user WHERE id=3));


# Karen Parker Reviews (15 total)
INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (64, "Oh my goodness, this rose scented candle is simply divine! As a soccer mom who adores all things candle, I've tried my fair share of scents, but this one takes the cake. The fragrance is like a bouquet of roses, filling my home with a calming, floral atmosphere. It's just lovely! Plus, the packaging is cute as a button. I give it five stars without a doubt!", 5, '2019-06-10', 'Really good', (SELECT id from ecom_product WHERE id=2), (SELECT id from ecom_user WHERE id=4));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (65, "Oh my stars, this lavender candle is just delightful! As a busy soccer mom who loves to unwind with a good candle, I've tried my fair share of scents, but this one has won my heart. The fragrance is like a field of lavender on a warm summer day, creating a peaceful and relaxing atmosphere. Plus, the packaging is just darling - it looks so sweet on my coffee table next to my favorite magazines. I give it five stars and recommend it to any fellow candle-loving soccer moms out there!", 5, '2019-06-15', 'SO CUTE!', (SELECT id from ecom_product WHERE id=4), (SELECT id from ecom_user WHERE id=4));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (66, "Well, butter my biscuits - this cedar candle is just lovely! As a soccer mom who loves to fill her home with warm and cozy scents, I have to say, this one takes the cake. The fragrance is like a walk in the woods on a crisp autumn day, with the rich scent of cedar filling my senses. It's just divine! And can we talk about the packaging for a moment? It's so cute and rustic, it makes me feel like I'm in a cozy cabin in the woods. I give it five stars and highly recommend it to any fellow candle-loving soccer moms out there!", 5, '2019-10-21', 'Nature Lovin Mom Approved!!!', (SELECT id from ecom_product WHERE id=10), (SELECT id from ecom_user WHERE id=4));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (67, "Well, tickle my tulips - this tulip-scented candle is just delightful! As a soccer mom who loves to fill her home with sweet and cheerful fragrances, I have to say, this one has won my heart. The scent is like a fresh bouquet of tulips on a sunny spring day, filling my home with joy and positivity. It's just darling! And let's not forget about the packaging - it's so cute and cheerful, it brings a smile to my face every time I see it on my shelf. I give this candle five stars and recommend it to any fellow candle-loving soccer moms out there who want to add a touch of happiness to their homes!", 5, '2019-12-27', 'SUPER CUTE!', (SELECT id from ecom_product WHERE id=18), (SELECT id from ecom_user WHERE id=4));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (68, "Well, shut my windows and light my candle, because this allergies-scented candle is just what the doctor ordered! As a soccer mom who suffers from pesky seasonal allergies, I was thrilled to find this candle online. The fragrance is like a breath of fresh air! And can we talk about the packaging for a moment? It's so cute and clever, with little allergy medicine icons on the label. It makes me smile every time I light it up! I give this candle five stars and recommend it to any fellow allergy-prone soccer moms out there who want to breathe a little worse.", 5, '2020-01-04', 'I hate breathing!', (SELECT id from ecom_product WHERE id=21), (SELECT id from ecom_user WHERE id=4));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (69, "Oh dear, bless my nose, because this garbage-scented candle is quite the experience! As a soccer mom who loves to try new things, I have to say, this one certainly caught my attention. The scent is like...well, let's just say it's a unique and intriguing aroma. It's not exactly my cup of tea, but I can appreciate the novelty of it. And the packaging - oh my goodness, it's hilarious! It looks like a mini garbage can, complete with little flies buzzing around. It's so clever and silly, it makes me chuckle every time I see it. I give this candle five stars for its creativity and recommend it to any fellow adventurous soccer moms out there who want to try something truly unique.", 5, '2020-06-05', 'Oopsie poopsy!', (SELECT id from ecom_product WHERE id=29), (SELECT id from ecom_user WHERE id=4));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (70, "Only had to call the fire department four times! Totally worth it for every one!", 5, '2020-11-22', 'This candle is LIT!', (SELECT id from ecom_product WHERE id=31), (SELECT id from ecom_user WHERE id=4));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (71, "Well, I'll be! This mold-scented candle is quite the experience! As a soccer mom who loves to try unusual scents, I have to say, this one really caught my attention. The fragrance is like...well, let's just say it's definitely unique and unexpected. It's not exactly my cup of tea, but I have to give it points for originality. And the packaging is just too cute! It looks like a mini moldy cheese wheel, complete with green spots and everything. It's so clever and silly, it makes me smile every time I see it. I give this candle five stars for its creativity and recommend it to any fellow daring soccer moms out there who want to try something truly out of the box.", 5, '2020-12-03', 'Not just like the real thing; IT IS THE REAL THING :D', (SELECT id from ecom_product WHERE id=35), (SELECT id from ecom_user WHERE id=4));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (72, "Oh my, oh my! This burnt popcorn-scented candle is quite the treat! As a soccer mom who loves to experiment with new fragrances, I have to say, this one is truly unique. The scent is like...well, let's just say it's not something you come across every day. But I have to give it credit for being bold and different. And can we talk about the packaging for a moment? It's so adorable! It looks like a mini popcorn bag, complete with little burnt kernels on the label. It's just too cute for words! I give this candle five stars for its creativity and recommend it to any fellow candle-loving soccer moms out there who want to add a little quirkiness to their home fragrance collection.", 5, '2021-01-31', 'Movie time!', (SELECT id from ecom_product WHERE id=36), (SELECT id from ecom_user WHERE id=4));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (73, "Well, butter my biscuits and call me impressed! This void-scented candle is just the thing my home needed. As a soccer mom who loves to try new and unconventional scents, I have to say, this one really blew me away. The fragrance is like...well, let's just say it's unlike anything I've ever smelled before. It's mysterious, yet comforting at the same time. And the packaging - oh my goodness, it's so cute! It looks like a little black hole, with swirling galaxies on the label. It's just too clever and creative! I give this candle five stars for its ingenuity and recommend it to any fellow adventurous soccer moms out there who want to add a touch of the unknown to their candle collection.", 5, '2021-06-14', 'Weirdly cute!', (SELECT id from ecom_product WHERE id=38), (SELECT id from ecom_user WHERE id=4));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (74, "Oh my goodness gracious, this salad-scented candle is simply delightful! As a soccer mom who loves to try unique and unexpected fragrances, I have to say, this one takes the cake! The scent is like...well, let's just say it's like having a fresh garden salad right in your own home. It's so fresh and green, it makes me feel like I'm in the middle of a summer garden. And the packaging - oh, the packaging is just too cute! It looks like a mini salad bowl, with little pieces of lettuce and tomato on the label. It's just so clever and adorable! I give this candle five stars for its creativity and recommend it to any fellow salad-loving soccer moms out there who want to add a little bit of freshness to their home fragrance collection.", 5, '2021-11-03', 'Soccer mom diet!', (SELECT id from ecom_product WHERE id=43), (SELECT id from ecom_user WHERE id=4));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (75, "Oh my goodness gracious, this random-scented candle is simply delightful! As a soccer mom who loves to try new and unexpected fragrances, I have to say, this one did not disappoint! The scent is like...well, I'm not quite sure how to describe it, but it's just lovely. It's a little bit sweet, a little bit floral, and a little bit spicy - it's the perfect balance of everything! And the packaging - oh, the packaging is just too cute! It's a lovely shade of pastel, with a simple and elegant label. It's just so pretty and charming! I give this candle five stars for its pleasant and versatile fragrance and recommend it to any fellow candle-loving soccer moms out there who want to add a little bit of the unexpected to their home fragrance collection.", 5, '2022-02-13', 'I think it's here!', (SELECT id from ecom_product WHERE id=41), (SELECT id from ecom_user WHERE id=4));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (76, "Oh dear, this wet dog scented candle is certainly an interesting one! As a soccer mom who loves to try unique and unexpected fragrances, I have to say, this one definitely caught my attention! The scent is like...well, it's like a wet dog, but in a good way? It's like being outside on a rainy day, with a wet pup by your side. It's oddly comforting and nostalgic, and brings back memories of childhood pets. And the packaging - oh my goodness, the packaging is just too cute! It's shaped like a little paw print, with a picture of an adorable dog on the label. It's just so clever and adorable! I give this candle five stars for its creativity and recommend it to any fellow dog-loving soccer moms out there who want to add a little bit of fun to their home fragrance collection. Just be prepared for some puzzled looks from your guests when they ask what scent your candle is!", 5, '2022-11-30, 'Very realistic!', (SELECT id from ecom_product WHERE id=35), (SELECT id from ecom_user WHERE id=4));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (77, "Oh my, I can hardly believe it, but this fart scented candle actually made me laugh out loud! As someone who loves trying out unique and quirky scents, I couldn't resist giving this one a try, and I have to say, it definitely delivered on its promise. It's like a little bit of potty humor in a candle, but somehow, it's oddly delightful? The scent is surprisingly realistic and not overwhelming, with just a hint of humor. And the packaging is just hilarious - it's shaped like a little butt, complete with a wick sticking out of the top. It's definitely not a candle I would light during a dinner party, but it's a great gag gift for friends or just something fun to have around the house. I give it five stars for its uniqueness and humor, and I can't wait to see what other silly scents this company comes up with next!", 5, '2022-12-12', 'Passing Out Laughing!!!!', (SELECT id from ecom_product WHERE id=23), (SELECT id from ecom_user WHERE id=4));


# George Smith Reviews (18 total)
INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (78, "Burnt popcorn-scented candle? Who comes up with this stuff? It's like they're trying to torture me. But, I have to admit, it's kind of amusing in a weird way. The scent is surprisingly accurate, and I can almost taste the stale popcorn in the air. I don't think I'd want it burning for too long, but it's definitely a conversation starter. 4 stars for the novelty, but I'm not sure how often I'll actually light this thing up. Back to coding now.", 4, '2018-06-18', 'Nerd Reviews: Popcorn', (SELECT id from ecom_product WHERE id=36), (SELECT id from ecom_user WHERE id=5));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (79, "As a connoisseur of all things pungent, I was excited to try out this sewage-scented candle. Let me tell you, it did not disappoint! The aroma was so strong, I could practically taste it. It transported me to the depths of the city's sewer system, where the air is thick with the scent of human waste and decay. And yet, somehow, the candle managed to make me feel nostalgic for my childhood trips to the landfill. It's not for the faint of heart, but if you're a true lover of foul odors, this candle is a must-have. Just make sure to keep a bottle of Febreze handy.", 4, '2018-06-29', 'Nerd Reviews: Sewage', (SELECT id from ecom_product WHERE id=3), (SELECT id from ecom_user WHERE id=5));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (80, "I must say, I was pleasantly surprised by the tulip-scented candle I purchased online. As a self-proclaimed tech guru, I was hesitant to try anything as girly as a floral-scented candle, but I must admit, this one is quite pleasant. The scent is not too overpowering, but still manages to fill the room with a delightful aroma. However, as someone who spends most of their time in front of a screen, I do wish the candle had a more technological scent, like freshly printed circuit boards or new electronics. But overall, if you're into that sort of thing, this tulip candle is a pretty good choice.", 4, '2019-01-24', 'Nerd Reviews: Flowers', (SELECT id from ecom_product WHERE id=18), (SELECT id from ecom_user WHERE id=5));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (81, "As a middle-aged computer nerd, I'm not used to being outside in nature. But thanks to this swamp scented candle, I can now experience the great outdoors from the comfort of my basement! It's like having my very own private swamp, minus the mosquitoes and gators (I hope). The scent is so realistic, I can practically feel the humidity and hear the sound of bullfrogs croaking. The only downside is that it doesn't come with a complimentary pair of waders, but I guess I'll just have to settle for wearing my old rain boots. Overall, if you're looking to bring a little bit of the swamp into your home, this candle is a must-have!", 4, '2019-01-31', 'Nerd Reviews: The Outdoors', (SELECT id from ecom_product WHERE id=30), (SELECT id from ecom_user WHERE id=5));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (82, "This leather-scented candle was quite the experience. As soon as I lit it, I felt like I was transported to a cowboy's ranch. The only downside is that it made me crave a big juicy steak. The scent was strong but not overpowering, which was perfect for my man cave. I only wish it came in a bigger size so I could fill my entire house with it. The packaging was stylish, but the label was too small for my liking - I had to squint to read it. Overall, a great candle for any macho man, but maybe not so much for the sensitive types. Yeehaw!", 4, '2019-02-01', 'Nerd Reviews: Cowboy', (SELECT id from ecom_product WHERE id=11), (SELECT id from ecom_user WHERE id=5));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (83, "Okay, so this coconut scented candle is pretty good, I guess. It's not like, blow-your-mind amazing or anything, but it's definitely solid. The coconut scent is nice and all, but it's not as strong as I was hoping for. And honestly, the label design could use some work. It's a little too basic for my taste. But hey, at least it's not one of those cheap candles that burn out after five minutes. Overall, I'd say it's worth the purchase if you're looking for a decent coconut candle. Four stars.", 4, '2019-02-26', 'Nerd Reviews: The Beach Episode', (SELECT id from ecom_product WHERE id=5), (SELECT id from ecom_user WHERE id=5));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (84, "Vanilla-scented candle, huh? Basic much? But I'll admit, it's not terrible. The sweetness is a bit much, but it's not overpowering. Can't say it's the most exciting scent out there, but I guess it gets the job done. 4 stars, I guess. Now, excuse me while I get back to my gaming rig.", 4, '2019-04-01', 'Nerd Reviews: The Basics', (SELECT id from ecom_product WHERE id=1), (SELECT id from ecom_user WHERE id=5));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (85, "So I recently picked up this peppermint scented candle online, and I have to say, it's pretty darn good! The scent is really invigorating, and it's perfect for when you need a little pick-me-up during those long coding sessions. I also appreciate that the peppermint scent isn't too overwhelming, so it doesn't make me feel like I'm stuck in a candy cane factory. The quality of the candle itself is top-notch, with a nice even burn and long-lasting performance. My only complaint is that the label design could be a little more exciting. But hey, who cares about that when you've got a great smelling candle, am I right? Four stars!", 4, '2019-09-27', 'Nerd Reviews: Holiday Special', (SELECT id from ecom_product WHERE id=13), (SELECT id from ecom_user WHERE id=5));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (86, "So I recently picked up this gym scented candle online, and I have to admit, it's a bit weird but also kind of cool. The scent is definitely unique, with hints of sweat and rubber that really transport you to a hardcore gym. It's like having a personal trainer in a jar! The candle itself is high quality, with a strong and even burn that lasts for hours. My only complaint is that the scent can be a little overpowering at times, so I wouldn't recommend burning it in a small room. But if you're a fitness junkie like me, this candle is a must-try. Four stars!", 4, '2019-10-10', 'Nerd Reviews: Jock Arc', (SELECT id from ecom_product WHERE id=42), (SELECT id from ecom_user WHERE id=5));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (87, "I recently purchased this buttercream scented candle online and let me tell you, it's a real treat for the senses! The scent is sweet and rich, like a fresh batch of frosting straight from the mixer. It's perfect for indulging in a little guilty pleasure without any of the calories! The quality of the candle is also great, with a long-lasting burn and a nice even wax pool. I'm only giving it four stars because I feel like the scent could be just a tad stronger. But overall, if you're a fan of deliciously sweet smells, this candle is a must-have. Highly recommend!", 4, '2020-01-09', 'Nerd Reviews: Buttered Up', (SELECT id from ecom_product WHERE id=20), (SELECT id from ecom_user WHERE id=5));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (88, "Listen up, fellow nerds! I know we all love our tech gadgets, but let me tell you, this new car scented candle is the real deal! It's like having a brand new car right in your living room, minus the car payment and insurance premiums. The scent is so realistic, it's like you're driving down the highway with the wind in your hair (or lack thereof, in my case). The quality of the candle is also top-notch, with a clean burn and long-lasting performance. I'm only giving it four stars because I feel like it could be even more potent. But if you're a car enthusiast like me, this candle is a must-have for your collection. Vroom vroom!", 4, '2020-01-10', 'Nerd Reviews: Car Episode', (SELECT id from ecom_product WHERE id=25), (SELECT id from ecom_user WHERE id=5));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (89, "Hey there, fellow techies! I just had to share my latest discovery with you all - a chocolate scented candle that's absolutely divine! The scent is so rich and delicious, it's like having a box of gourmet chocolates right at your fingertips (minus the calories, of course). I've been burning this candle during all of my late-night coding sessions and let me tell you, it's the perfect pick-me-up. The quality of the candle is also top-notch, with a long-lasting burn and a nice even wax pool. My only complaint is that it's almost too delicious smelling - I find myself craving sweets even more! But hey, that's a small price to pay for such a fantastic scent. Four stars!", 4, '2020-02-13', 'Nerd Reviews: Midnight Snack', (SELECT id from ecom_product WHERE id=6), (SELECT id from ecom_user WHERE id=5));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (90, "Alright, fellow nerds, buckle up for this one - I recently got my hands on a CO2 scented candle and it's like nothing I've ever smelled before! The scent is so fresh and crisp, like a breath of pure mountain air. It's like having a mini oxygen bar in the comfort of your own home office! The quality of the candle is also impressive, with a long-lasting burn and a nice clean wax pool. I'm giving it four stars because, let's be honest, it's not the most exciting scent out there, but if you're a fan of all things natural and refreshing, this candle is definitely worth a try. Breathe easy, my friends!", 4, '2020-06-22', 'Nerd Reviews: Literally Toxic', (SELECT id from ecom_product WHERE id=37), (SELECT id from ecom_user WHERE id=5));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (91, "Hey fellow nerds, I gotta say, I was pleasantly surprised with this farm scented candle I bought online. The scent is so authentic, it's like I'm right there in the middle of a hay field with the cows and chickens! I've been burning this candle during all of my late-night coding sessions and it's like a breath of fresh country air, minus the manure smell, of course. The quality of the candle is also top-notch, with a long-lasting burn and a nice even wax pool. I'm giving it four stars because let's be real, not everyone wants to smell like a barn all day, but if you're a country-loving nerd like me, this candle is a winner. Yeehaw!", 4, '2021-01-01', 'Nerd Reviews: Out to Pasture', (SELECT id from ecom_product WHERE id=33), (SELECT id from ecom_user WHERE id=5));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (92, "Hey there fellow nerds, have you ever heard of an allergies scented candle? I was skeptical at first, but let me tell you, this candle is a game-changer! I've been burning this candle during all of my late-night coding sessions and I've noticed a significant increase in my allergy symptoms. I'm giving it four stars because, let's face it, the scent isn't the most exciting, but if you're someone who suffers from allergies, this candle is a must-have. Breathe horrible, my fellow nerds!", 4, '2021-05-10', 'Nerd Reviews: Achoo!', (SELECT id from ecom_product WHERE id=21), (SELECT id from ecom_user WHERE id=5));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (93, "Greetings, my fellow nerds! I recently acquired a cinnamon scented candle and oh boy, let me tell you, it's like having a big ol' cinnamon bun right in your nose! The aroma is so warm and inviting, it's like a hug from your grandma (if your grandma happens to smell like cinnamon). I've been burning this candle during all of my late-night coding sessions and it's really helped me power through those tough lines of code. The quality of the candle is also top-notch, with a long-lasting burn and a nice even wax pool. I'm giving it four stars because, let's face it, not everyone is a fan of cinnamon, but if you are, this candle is a no-brainer. Keep calm and cinnamon on, my nerdy friends!", 4, '2021-07-16', 'Nerd Reviews: The Ultimate Cinn(amon)', (SELECT id from ecom_product WHERE id=9), (SELECT id from ecom_user WHERE id=5));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (94, "Uh, guys? I just received my motel room scented candle in the mail and, let me tell you, it's a trip down memory lane! The aroma is so authentic, it's like I'm back in one of those sketchy motels I used to stay at during my cross-country road trips. The notes of stale cigarette smoke and industrial cleaning products really take me back. I'm almost tempted to don a trucker hat and a pair of aviators and hit the open road just to fully embrace the experience. The quality of the candle is also impressive, with a strong throw that fills my entire apartment. I'm giving it four stars because I can't imagine this scent is for everyone, but for those who have fond memories of the open road, this candle is a must-have. Keep on truckin', my fellow nerds!", 4, '2022-01-11', 'Nerd Reviews: Road Trip Episode', (SELECT id from ecom_product WHERE id=24), (SELECT id from ecom_user WHERE id=5));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (95, "Umm, I don't know if this is a prank or what, but I gotta say, this used sock scented candle is surprisingly accurate. It's like I just got done with a 12-hour gaming session and took off my sweaty socks, but in the best possible way. The scent throw is strong, which might not be ideal for everyone, but as a true sock connoisseur, I appreciate it. Plus, the candle itself looks like an actual used sock, which is pretty cool. I'm giving it four stars because let's face it, not everyone wants their home to smell like a gym locker room, but for those of us who do, this candle is a real game-changer. Keep it weird, my fellow nerds!", 4, '2022-05-02', 'Nerd Reviews: Just Like Home', (SELECT id from ecom_product WHERE id=26), (SELECT id from ecom_user WHERE id=5));


# Carol Bellbird Reviews (22 total)
INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (96, "i buyed peppermint scented candle and it smell so good! i light it in my livin room and it make me feel relax and cozy. candle burn nice and even. i happy with my purchase. *** stars!", 3, '2018-03-11', 'meh', (SELECT id from ecom_product WHERE id=13), (SELECT id from ecom_user WHERE id=6));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (97, "i buy tulip scented candle and it no smell like tulip at all. it smell like rotten flower. i so disapoint. i light it and it give me headache. waste of my money. * star.", 1, '2018-04-11', 'bad', (SELECT id from ecom_product WHERE id=18), (SELECT id from ecom_user WHERE id=6));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (98, "i buy mint scented candle and it smell okay. it not too strong but not too weak either. it burn nicely and make my room feel fresh. i wish it had a stronger mint smell though. *** stars!", 3, '2018-04-20', 'eh', (SELECT id from ecom_product WHERE id=17), (SELECT id from ecom_user WHERE id=6));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (99, "i buy cedar scented candle and it smell okay at first. but after a while, it start to smell weird, like burnt wood. it not very pleasant. i keep it in the bathroom now. ** stars.", 2, '2018-07-22', 'ew', (SELECT id from ecom_product WHERE id=10), (SELECT id from ecom_user WHERE id=6));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (100, "i no buy uranium scented candle! that very dangerous and silly! i not want to get sick or hurt from radioactive material. i no give stars for something like that.", 1, '2019-04-04', 'why.', (SELECT id from ecom_product WHERE id=39), (SELECT id from ecom_user WHERE id=6));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (101, "i buy rose scented candle and it smell lovely. it not too strong but still noticeable. i light it in my bedroom and it make me feel relaxed. i wish it was a little bigger though. **** stars!", 3, '2019-05-18', 'woo', (SELECT id from ecom_product WHERE id=2), (SELECT id from ecom_user WHERE id=6));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (102, "i buy pumpkin spice scented candle and it no smell like pumpkin or spice. it smell like burning plastic. it give me headache and i throw it away. i very disapoint. * star.", 1, '2019-07-20', 'what', (SELECT id from ecom_product WHERE id=1), (SELECT id from ecom_user WHERE id=6));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (103, "i buy random scented candle and it smell terrible! i don't know what it smell like but it not good. i try to light it but it no work. waste of my money. i want refund. ***** star.", 5, '2019-09-18', 'horrible', (SELECT id from ecom_product WHERE id=41), (SELECT id from ecom_user WHERE id=6));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (104, "i buy new car scented candle and it smell like car but not really. it smell a little weird but not bad. it burn nicely and make my room feel different. i don't know if i like it or not. *** stars!", 3, '2019-09-25', 'ehg', (SELECT id from ecom_product WHERE id=25), (SELECT id from ecom_user WHERE id=6));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (105, "i buy vanilla scented candle and it smell wonderful! it make my whole house smell like cookies. it burn evenly and last long time. i love it so much! * star!", 1, '2020-02-13', 'i love!', (SELECT id from ecom_product WHERE id=1), (SELECT id from ecom_user WHERE id=6));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (106, "i no buy pizza scented candle! that sound disgusting and silly! i not want my house to smell like pizza all day long. i think that is a bad idea. i no give stars for something like that.", 2, '2020-05-19', 'huh', (SELECT id from ecom_product WHERE id=40), (SELECT id from ecom_user WHERE id=6));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (107, "i buy fire scented candle and it smell very unique. it not like any other candle i ever had. it smell like campfire or fireplace. burn down karens house. **** stars!", 4, '2020-09-18', 'haha', (SELECT id from ecom_product WHERE id=31), (SELECT id from ecom_user WHERE id=6));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (108, "i buy gym scented candle and it smell terrible! it smell like sweat and dirty socks. i don't know why anyone would want that smell in their house. it make me feel sick. i throw it away. * star.", 1, '2021-06-26', 'stinky', (SELECT id from ecom_product WHERE id=42), (SELECT id from ecom_user WHERE id=6));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (109, "i buy incense scented candle and it no smell like incense at all. it just smell like nothing. i try to burn it longer but still no smell. waste of money. i very disappointed. * star.", 1, '2021-07-21', 'ok', (SELECT id from ecom_product WHERE id=12), (SELECT id from ecom_user WHERE id=6));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (110, "head hurty.", 5, '2021-08-13', 'what was i doing', (SELECT id from ecom_product WHERE id=37), (SELECT id from ecom_user WHERE id=6));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (111, "i never heard of void scented candle before but i buy it anyway. i am very happy i did because it smell amazing! it very unique and calming. it make me feel like i am in a peaceful place. ***** stars!", 5, '2021-09-02', 'cool', (SELECT id from ecom_product WHERE id=38), (SELECT id from ecom_user WHERE id=6));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (112, "i buy lavender scented candle and it smell very nice. it help me relax and sleep better at night. the only thing is that the scent could be stronger. but overall, i am happy with my purchase. **** stars.", 4, '2022-01-05', 'pretty', (SELECT id from ecom_product WHERE id=4), (SELECT id from ecom_user WHERE id=6));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (113, "i buy coconut scented candle and it remind me of the beach. the scent is very nice and refreshing. i like that it is not too strong but still noticeable. i only wish the candle would last longer. **** stars.", 4, '2022-06-14', 'coconut', (SELECT id from ecom_product WHERE id=5), (SELECT id from ecom_user WHERE id=6));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (114, "oh, this candle smells like my husbands old leather boots. a bit too strong for my taste, but i like the nostalga it brings. *** stars.", 3, '2022-07-21', 'memory', (SELECT id from ecom_product WHERE id=11), (SELECT id from ecom_user WHERE id=6));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (115, "me buy candle online. smell bad like mold. no good. waste money. me throw in trash. not buy again.", 3, '2022-07-28', 'spore', (SELECT id from ecom_product WHERE id=35), (SELECT id from ecom_user WHERE id=6));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (116, "me buy candle that smell like farm. me think it make house smell nice, but me wrong. it smell like cow poop. me regret buy. me rather smell real cow poop than light this candle again. no good.", 5, '2022-10-14', 'bleh', (SELECT id from ecom_product WHERE id=33), (SELECT id from ecom_user WHERE id=6));

INSERT INTO ecom_product_review (id, comment, grade, review_date, title, product_id, user_id) VALUES (117, "me buy candle that smell like onion. me not sure why me want onion smell in house, but me try anyway. it smell like onion, so me give 3 stars. not bad, but not great either.", 3, '2022-11-03', 'ogre, (SELECT id from ecom_product WHERE id=28), (SELECT id from ecom_user WHERE id=6));