# Main Docker-Compose File
# Authors: Sean Kells <spk3077@rit.edu>, Cameron MacDonald <chm7374@rit.edu>
version: "3"

services:
  # Database
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: csec77499981
       MYSQL_DATABASE: csec
       # MYSQL_USER: root
       # MYSQL_PASSWORD: csec77499981
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=csec77499981 --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 15
    ports:
       - 3306:3306

  # Maven SpringBoot (Complete)
  api:
    hostname: api
    build:
      context: ../
      dockerfile: API_Dockerfile

  # Web Server (Complete)
  node_app:
    hostname: node_app
    build:
      context: ../src/main/frontend
      dockerfile: Dockerfile
    command: ng serve --ssl true --open
    ports:
      - 80:80
      - 443:443
   
  # PHPMYADMIN Interface
  phpmyadmin:
    hostname: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - 8080:80



 
