# Main Docker-Compose File
# Authors: Sean Kells <spk3077@rit.edu>, Cameron MacDonald <chm7374@rit.edu>
version: "2.4"

services:
  # Maven SpringBoot
  api:
    build:
      context: ../
      dockerfile: API_Dockerfile
    hostname: api
    #command: java -jar /usr/local/lib/candle.jar
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/csec?testdbautoReconnect=true&failOverReadOnly=false&maxReconnects=10
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: csec77499981
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
      - frontend

  # Database (Complete)
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    hostname: db
    environment:
       MYSQL_ROOT_PASSWORD: csec77499981
       MYSQL_DATABASE: csec
       MYSQL_ROOT_USER: root
       MYSQL_USER: csec
       MYSQL_PASSWORD: csec77499981
       #MYSQL_TCP_PORT: 3306
    healthcheck:
      test: ["CMD", "mysqladmin", 'ping', '-h', 'localhost', '-u', 'csec', '-p=csec77499981']
      interval: 2s
      timeout: 20s
      retries: 15
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
    ports:
       - 3306:3306

  # Web Server (Complete)
  node_app:
    hostname: node_app
    container_name: node_app
    build:
      context: ../src/main/frontend
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    networks:
      - frontend
   
  # PHPMYADMIN Interface (Complete)
  phpmyadmin:
    hostname: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - 8080:80
    networks:
      - backend

  # Fill out the sql database
  #sql_filler:
  #  build:
  #    context: ../src/main/sqlInserts
  #    dockerfile: Dockerfile
  #  depends_on:
  #    db:
  #      condition: service_healthy


volumes:
  db-data:

networks:
  backend:
  frontend:
